/**
 * Sample Plant Data for Bloomify
 * Comprehensive dataset with 20 diverse plants covering:
 * - Different space types (indoor, balcony, terrace, garden)
 * - Various sunlight requirements (low, medium, high)
 * - Different climate preferences
 * - Multiple maintenance levels
 */

const plantsData = [
  {
    name: "Monstera Deliciosa",
    scientificName: "Monstera deliciosa",
    description: "Large-leafed tropical plant with unique split leaves. Easy to care for and adds dramatic appeal.",
    temperature_range: { min: 16, max: 27 },
    humidity: { min: 50, max: 80, preference: "moderate" },
    sunlight: "medium",
    space: ["indoor", "balcony"],
    spaceSize: "medium",
    soil: ["well-draining", "loamy"],
    water_need: "moderate",
    watering_frequency: "every 1-2 weeks",
    maintenance: "low",
    region: ["tropical", "subtropical"],
    hardiness_zone: "10-12",
    growth_rate: "fast",
    max_height: "3-4 m",
    toxicity: "toxic",
    petFriendly: false
  },
  {
    name: "Snake Plant",
    scientificName: "Sansevieria trifasciata",
    description: "Extremely hardy succulent with long, sword-like leaves. Perfect for low-light conditions.",
    temperature_range: { min: 13, max: 32 },
    humidity: { min: 20, max: 50, preference: "dry" },
    sunlight: "low",
    space: ["indoor"],
    spaceSize: "small",
    soil: ["well-draining", "sandy"],
    water_need: "low",
    watering_frequency: "every 2-3 weeks",
    maintenance: "low",
    region: ["tropical", "subtropical", "temperate"],
    hardiness_zone: "10-12",
    growth_rate: "slow",
    max_height: "1.5 m",
    toxicity: "mildly toxic",
    petFriendly: false
  },
  {
    name: "Pothos",
    scientificName: "Epipremnum aureum",
    description: "Trailing vine with heart-shaped leaves. Excellent for beginners and adapts to various lighting.",
    temperature_range: { min: 15, max: 30 },
    humidity: { min: 50, max: 70, preference: "moderate" },
    sunlight: "low",
    space: ["indoor", "balcony"],
    spaceSize: "small",
    soil: ["well-draining", "loamy"],
    water_need: "moderate",
    watering_frequency: "weekly",
    maintenance: "low",
    region: ["tropical", "subtropical"],
    hardiness_zone: "10-12",
    growth_rate: "fast",
    max_height: "2-3 m",
    toxicity: "toxic",
    petFriendly: false
  },
  {
    name: "Philodendron",
    scientificName: "Philodendron hederaceum",
    description: "Vining plant with glossy leaves. Highly adaptable and great for hanging baskets.",
    temperature_range: { min: 15, max: 29 },
    humidity: { min: 50, max: 75, preference: "moderate" },
    sunlight: "low",
    space: ["indoor", "balcony"],
    spaceSize: "small",
    soil: ["well-draining", "loamy"],
    water_need: "moderate",
    watering_frequency: "every 1-2 weeks",
    maintenance: "low",
    region: ["tropical", "subtropical"],
    hardiness_zone: "10-12",
    growth_rate: "medium",
    max_height: "2 m",
    toxicity: "toxic",
    petFriendly: false
  },
  {
    name: "Spider Plant",
    scientificName: "Chlorophytum comosum",
    description: "Classic houseplant with arching green and white striped leaves. Produces baby plants naturally.",
    temperature_range: { min: 13, max: 29 },
    humidity: { min: 40, max: 60, preference: "dry" },
    sunlight: "medium",
    space: ["indoor", "balcony"],
    spaceSize: "small",
    soil: ["well-draining", "loamy"],
    water_need: "moderate",
    watering_frequency: "weekly",
    maintenance: "low",
    region: ["tropical", "subtropical", "temperate"],
    hardiness_zone: "9-11",
    growth_rate: "medium",
    max_height: "60 cm",
    toxicity: "safe",
    petFriendly: true
  },
  {
    name: "Peace Lily",
    scientificName: "Spathiphyllum wallisii",
    description: "Elegant plant with glossy dark leaves and white flowers. Indicates when it needs water by drooping.",
    temperature_range: { min: 16, max: 27 },
    humidity: { min: 50, max: 80, preference: "high" },
    sunlight: "low",
    space: ["indoor"],
    spaceSize: "small",
    soil: ["well-draining", "loamy"],
    water_need: "moderate",
    watering_frequency: "every 1-2 weeks",
    maintenance: "low",
    region: ["tropical", "subtropical"],
    hardiness_zone: "11-12",
    growth_rate: "medium",
    max_height: "1 m",
    toxicity: "mildly toxic",
    petFriendly: false
  },
  {
    name: "Rubber Plant",
    scientificName: "Ficus elastica",
    description: "Stunning plant with large, glossy leaves. Makes a bold statement in any space.",
    temperature_range: { min: 15, max: 27 },
    humidity: { min: 40, max: 60, preference: "dry" },
    sunlight: "medium",
    space: ["indoor", "balcony"],
    spaceSize: "large",
    soil: ["well-draining", "loamy"],
    water_need: "moderate",
    watering_frequency: "every 1-2 weeks",
    maintenance: "medium",
    region: ["tropical", "subtropical"],
    hardiness_zone: "10-12",
    growth_rate: "medium",
    max_height: "2-3 m",
    toxicity: "mildly toxic",
    petFriendly: false
  },
  {
    name: "Succulents Mix (Echeveria)",
    scientificName: "Echeveria agavoides",
    description: "Colorful, low-maintenance succulent with geometric rosette forms. Perfect for dry spaces.",
    temperature_range: { min: 10, max: 32 },
    humidity: { min: 10, max: 30, preference: "dry" },
    sunlight: "high",
    space: ["indoor", "balcony", "terrace"],
    spaceSize: "small",
    soil: ["well-draining", "sandy"],
    water_need: "low",
    watering_frequency: "every 2-3 weeks",
    maintenance: "low",
    region: ["temperate", "arid"],
    hardiness_zone: "9-11",
    growth_rate: "slow",
    max_height: "30 cm",
    toxicity: "safe",
    petFriendly: true
  },
  {
    name: "Aloe Vera",
    scientificName: "Aloe barbadensis miller",
    description: "Medicinal succulent with gel-filled leaves. Great for sunny spots and minimal watering.",
    temperature_range: { min: 13, max: 27 },
    humidity: { min: 10, max: 30, preference: "dry" },
    sunlight: "high",
    space: ["indoor", "balcony", "terrace"],
    spaceSize: "small",
    soil: ["well-draining", "sandy"],
    water_need: "low",
    watering_frequency: "every 3 weeks",
    maintenance: "low",
    region: ["arid", "subtropical"],
    hardiness_zone: "9-12",
    growth_rate: "slow",
    max_height: "60 cm",
    toxicity: "safe",
    petFriendly: true
  },
  {
    name: "Fiddle Leaf Fig",
    scientificName: "Ficus lyrata",
    description: "Trendy plant with large, lyre-shaped leaves. Makes a dramatic statement in bright spaces.",
    temperature_range: { min: 15, max: 28 },
    humidity: { min: 40, max: 60, preference: "moderate" },
    sunlight: "high",
    space: ["indoor", "balcony"],
    spaceSize: "large",
    soil: ["well-draining", "loamy"],
    water_need: "moderate",
    watering_frequency: "every 1-2 weeks",
    maintenance: "medium",
    region: ["tropical", "subtropical"],
    hardiness_zone: "10-12",
    growth_rate: "medium",
    max_height: "2-3 m",
    toxicity: "mildly toxic",
    petFriendly: false
  },
  {
    name: "Pothes Golden",
    scientificName: "Epipremnum aureum var. golden",
    description: "Golden variety of pothos with bright yellow-green leaves. Perfect for adding color to dim areas.",
    temperature_range: { min: 15, max: 30 },
    humidity: { min: 50, max: 70, preference: "moderate" },
    sunlight: "low",
    space: ["indoor", "balcony"],
    spaceSize: "small",
    soil: ["well-draining", "loamy"],
    water_need: "moderate",
    watering_frequency: "weekly",
    maintenance: "low",
    region: ["tropical", "subtropical"],
    hardiness_zone: "10-12",
    growth_rate: "fast",
    max_height: "2 m",
    toxicity: "toxic",
    petFriendly: false
  },
  {
    name: "Bamboo Palm",
    scientificName: "Chamaedorea seifrizii",
    description: "Tropical palm with delicate leaflets. Great for creating a tropical atmosphere indoors.",
    temperature_range: { min: 13, max: 26 },
    humidity: { min: 50, max: 70, preference: "moderate" },
    sunlight: "low",
    space: ["indoor"],
    spaceSize: "large",
    soil: ["well-draining", "loamy"],
    water_need: "moderate",
    watering_frequency: "every 1-2 weeks",
    maintenance: "medium",
    region: ["tropical", "subtropical"],
    hardiness_zone: "9-11",
    growth_rate: "slow",
    max_height: "2 m",
    toxicity: "safe",
    petFriendly: true
  },
  {
    name: "Boston Fern",
    scientificName: "Nephrolepis exaltata",
    description: "Classic fern with feathery fronds. Loves humidity and bright, indirect light.",
    temperature_range: { min: 15, max: 24 },
    humidity: { min: 60, max: 80, preference: "high" },
    sunlight: "medium",
    space: ["indoor", "balcony"],
    spaceSize: "medium",
    soil: ["well-draining", "loamy"],
    water_need: "high",
    watering_frequency: "every 2-3 days",
    maintenance: "medium",
    region: ["tropical", "temperate"],
    hardiness_zone: "9-12",
    growth_rate: "medium",
    max_height: "60 cm",
    toxicity: "safe",
    petFriendly: true
  },
  {
    name: "ZZ Plant",
    scientificName: "Zamioculcas zamiifolia",
    description: "Ultra-hardy plant with glossy leaflets. Thrives on neglect and low light.",
    temperature_range: { min: 13, max: 30 },
    humidity: { min: 20, max: 50, preference: "dry" },
    sunlight: "low",
    space: ["indoor"],
    spaceSize: "medium",
    soil: ["well-draining", "loamy"],
    water_need: "low",
    watering_frequency: "every 2-3 weeks",
    maintenance: "low",
    region: ["tropical", "subtropical", "temperate"],
    hardiness_zone: "9-12",
    growth_rate: "slow",
    max_height: "90 cm",
    toxicity: "mildly toxic",
    petFriendly: false
  },
  {
    name: "Dracaena Dragon Tree",
    scientificName: "Dracaena marginata",
    description: "Elegant plant with slender, red-edged leaves. Adds height and visual interest to corners.",
    temperature_range: { min: 15, max: 27 },
    humidity: { min: 30, max: 50, preference: "dry" },
    sunlight: "medium",
    space: ["indoor"],
    spaceSize: "large",
    soil: ["well-draining", "loamy"],
    water_need: "low",
    watering_frequency: "every 2 weeks",
    maintenance: "low",
    region: ["tropical", "subtropical"],
    hardiness_zone: "10-12",
    growth_rate: "slow",
    max_height: "2-3 m",
    toxicity: "mildly toxic",
    petFriendly: false
  },
  {
    name: "Dieffenbachia",
    scientificName: "Dieffenbachia seguine",
    description: "Striking variegated plant with cream and green leaves. Loves bright, indirect light.",
    temperature_range: { min: 18, max: 27 },
    humidity: { min: 60, max: 75, preference: "high" },
    sunlight: "medium",
    space: ["indoor"],
    spaceSize: "medium",
    soil: ["well-draining", "loamy"],
    water_need: "moderate",
    watering_frequency: "every 1-2 weeks",
    maintenance: "medium",
    region: ["tropical", "subtropical"],
    hardiness_zone: "10-12",
    growth_rate: "medium",
    max_height: "1.5 m",
    toxicity: "toxic",
    petFriendly: false
  },
  {
    name: "String of Pearls",
    scientificName: "Senecio rowleyanus",
    description: "Unique succulent with bead-like leaves. Perfect for hanging baskets and bright spaces.",
    temperature_range: { min: 10, max: 27 },
    humidity: { min: 20, max: 40, preference: "dry" },
    sunlight: "high",
    space: ["indoor", "balcony", "terrace"],
    spaceSize: "small",
    soil: ["well-draining", "sandy"],
    water_need: "low",
    watering_frequency: "every 2-3 weeks",
    maintenance: "medium",
    region: ["arid", "subtropical"],
    hardiness_zone: "9-11",
    growth_rate: "medium",
    max_height: "60 cm",
    toxicity: "safe",
    petFriendly: true
  },
  {
    name: "Calathea Orbifolia",
    scientificName: "Goeppertia orbifolia",
    description: "Stunning prayer plant with silver-green leaves. Requires humid conditions and filtered light.",
    temperature_range: { min: 16, max: 27 },
    humidity: { min: 60, max: 80, preference: "high" },
    sunlight: "medium",
    space: ["indoor"],
    spaceSize: "medium",
    soil: ["well-draining", "loamy"],
    water_need: "moderate",
    watering_frequency: "every 1-2 weeks",
    maintenance: "high",
    region: ["tropical", "subtropical"],
    hardiness_zone: "11-12",
    growth_rate: "slow",
    max_height: "60 cm",
    toxicity: "safe",
    petFriendly: true
  },
  {
    name: "Pilea Peperomioides",
    scientificName: "Pilea peperomioides",
    description: "Trendy 'money plant' with coin-shaped leaves. Low-maintenance and perfect for shelves.",
    temperature_range: { min: 15, max: 25 },
    humidity: { min: 40, max: 60, preference: "moderate" },
    sunlight: "medium",
    space: ["indoor", "balcony"],
    spaceSize: "small",
    soil: ["well-draining", "loamy"],
    water_need: "moderate",
    watering_frequency: "weekly",
    maintenance: "low",
    region: ["tropical", "subtropical"],
    hardiness_zone: "10-12",
    growth_rate: "medium",
    max_height: "40 cm",
    toxicity: "safe",
    petFriendly: true
  },
  {
    name: "African Violet",
    scientificName: "Saintpaulia ionantha",
    description: "Charming flowering plant with fuzzy leaves and purple flowers. Prefers bright, indirect light.",
    temperature_range: { min: 15, max: 24 },
    humidity: { min: 50, max: 70, preference: "moderate" },
    sunlight: "medium",
    space: ["indoor"],
    spaceSize: "small",
    soil: ["well-draining", "loamy"],
    water_need: "moderate",
    watering_frequency: "weekly",
    maintenance: "medium",
    region: ["tropical", "subtropical"],
    hardiness_zone: "11-12",
    growth_rate: "slow",
    max_height: "30 cm",
    toxicity: "safe",
    petFriendly: true
  },
  {
    name: "Anthurium",
    scientificName: "Anthurium andraeanum",
    description: "Tropical plant with heart-shaped, glossy leaves and exotic red flowers. Long-lasting blooms.",
    temperature_range: { min: 16, max: 27 },
    humidity: { min: 60, max: 80, preference: "high" },
    sunlight: "medium",
    space: ["indoor"],
    spaceSize: "medium",
    soil: ["well-draining", "loamy"],
    water_need: "moderate",
    watering_frequency: "every 1-2 weeks",
    maintenance: "medium",
    region: ["tropical", "subtropical"],
    hardiness_zone: "11-12",
    growth_rate: "slow",
    max_height: "90 cm",
    toxicity: "toxic",
    petFriendly: false
  },
  {
    name: "Jade Plant",
    scientificName: "Crassula ovata",
    description: "Thick-leaved succulent that resembles a small tree. Extremely hardy and drought-tolerant.",
    temperature_range: { min: 10, max: 27 },
    humidity: { min: 20, max: 40, preference: "dry" },
    sunlight: "high",
    space: ["indoor", "balcony", "terrace"],
    spaceSize: "medium",
    soil: ["well-draining", "sandy"],
    water_need: "low",
    watering_frequency: "every 2-3 weeks",
    maintenance: "low",
    region: ["arid", "subtropical"],
    hardiness_zone: "9-11",
    growth_rate: "slow",
    max_height: "1.5 m",
    toxicity: "safe",
    petFriendly: false
  }
];

module.exports = { plantsData };
